name: Build and Release

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Node-Version 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Run npm install, bundle and test
        run: |
          npm install
          npm run test:integration
        env:
          CI: true
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Commit Bundle
        run: |
          git checkout -b bundle/publish
          git config --local user.email ${{ secrets.SECRET_MAIL }}
          git config --local user.name "sipgateio-team"
          git add --force bundle/sipgate-io.js
          git commit -m "publish: version ${{ steps.get_version.outputs.VERSION }}" --no-verify
          git tag ${{ steps.get_version.outputs.VERSION }} --force
          git push --tags --force
      - name: Create GitHub Release
        uses: fnkr/github-action-ghr@v1.2
        env:
          GHR_PATH: bundle/sipgate-io.js
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
