name: Bundle and release

on:
  push:
    branches: master
    tags: v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Install dependencies and bundle
      run: |
        npm i
        npm run bundle
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.2
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GHR_PATH: bundle/sipgate-io.js
          GITHUB_TOKEN: ${{ github.token }}
